site_name: GiadadambNTA
site_url: https://giadadamb.github.io/nuovoprog/
theme: 
  name: material
  language: it
  logo: images/logo1.png 
 
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs  
    - navigation.tabs.sticky
    - toc.follow
    - search.suggest
    - search.highlight
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: teal
      accent: blue
  

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: teal
      accent: blue
  
  font:
    text: Kanit

markdown_extensions:

  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
 
plugins:
  - search
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
 
  
copyright: Copyright &copy; 2024 - 2025 Giada D'Ambrosio