site_name: GiadadambNTA
site_url: https://giadadamb.github.io/nuovoprog/

theme: 
  name: material
  language: it
  logo: images/logo1.png 
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs  
    - navigation.tabs.sticky
    - toc.follow
    - search.suggest
    - search.highlight
    - navigation.footer
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: teal
      accent: blue
  
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: teal
      accent: blue
  
  font:
    text: Prompt

nav:
  - Home: index.md
  - Biografia: about.md
  - Documentazione: Documentazione.md
  - NTAlab:
      - "Gruppo Trama": NTAlab/post/Gruppo-Trama.md
      - "Il Frottage": NTAlab/post/Il-Frottage.md
      - "La lente macro": NTAlab/post/La-lente-macro.md
      - "La Panoramica inversa": NTAlab/post/La-Panoramica-inversa.md
      - "Gruppo Bioplastica": NTAlab/post/Gruppo-Bioplastica.md
      - "La Catalogazione": NTAlab/post/La-Catalogazione.md


markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search

copyright: Copyright © 2024 - 2025 Giada D'Ambrosio
