site_name: GiadadambNTA
site_url: https://giadadamb.github.io/nuovoprog/
theme: 
  name: material
  language: it
  logo: images/logo1.png 
 
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs  
    - navigation.tabs.sticky
    - toc.follow
    - search.suggest
    - search.highlight
    - navigation.footer
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: teal
      accent: blue
  

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: teal
      accent: blue
  
  font:
    text: Kanit

markdown_extensions:

  - attr_list

plugins:
  - search
  
 
  
copyright: Copyright &copy; 2024 - 2025 Giada D'Ambrosio

markdown_extension:
  - admonition
  - pymdownx.details
  - pymdownx.superfences